app/helpers/gobierto_budgets/application_helper.rb
app/views/layouts/gobierto_budgets_application.html.erb
config/locales/views/layouts/ca.yml
config/locales/views/layouts/en.yml
config/locales/views/layouts/es.yml

This PR disables turbolinks in the maps page to load Carto assets just in this single page.

Disable turbolinks for maps

---

app/assets/javascripts/autocomplete_settings.js
app/assets/javascripts/gobierto_budgets/compare.js
app/assets/javascripts/gobierto_budgets/ui.js
app/views/gobierto_budgets/pages/_compare_big.html.erb
app/views/gobierto_budgets/places/show.js.erb
config/locales/views/ca.yml
config/locales/views/en.yml
config/locales/views/es.yml
config/locales/views/gobierto_budgets/ca.yml

This PR localizes the sentence for the autosuggest and fixes a typo.
Related with:
https://github.com/PopulateTools/gobierto-budgets-comparator-gen-cat/issues/40#issuecomment-266469775

Missing translation autocomplete

---

app/assets/javascripts/gobierto_budgets/maps.js
app/assets/stylesheets/gobierto_budgets/map_page.scss
app/views/gobierto_budgets/pages/map.html.erb

This PR fixes #24, creating an overlay spinner that is fired every time the user loads a new dataset, but not while zooming or panning.
It also styles the map metrics indicators while hovering.

Show a full screen overlay while loading new data

---

app/assets/javascripts/gobierto_budgets/compare.js

This PR fixes compare link on rankings page after a filter is applied.
Closes https://github.com/PopulateTools/gobierto-budgets-comparator-gen-cat/issues/69

Fix compare links after action in ranking

---

config/locales/views/gobierto_budgets/es.yml

I noticed that it says "Municipals" instead of "Municipales" in the home page at https://presupuestos.gobierto.es, this reverts the texts in the `es` locale file

Revert typo in es locale file

---

app/models/gobierto_budgets/search_engine_configuration.rb
lib/tasks/gobierto_budgets/budgets-import.rake

Connects to [#46](https://github.com/PopulateTools/populate-data-indicators/issues/46) 
Updates ElasticSearch mapping for budget lines execution series

Update ElasticSearch schema for budgets execution series

---

app/controllers/gobierto_budgets/places_controller.rb
config/routes.rb

So we fix the links in the maps. To ensure we don't break the existing URLs for the regular comparator nor the gencat one.
Links to a regular place, using slug:
* http://gencat-presupuestos.gobify.net/places/barcelona/2016
* http://presupuestos.gobify.net/places/alfambra/2018
Links to an associated entity (with and without year):
* http://gencat-presupuestos.gobify.net/places/barcelona/institut-municipal-d-informatica-de-barcelona/2016
* http://gencat-presupuestos.gobify.net/places/barcelona/institut-municipal-d-informatica-de-barcelona
The map links:
* http://presupuestos.gobify.net/mapas/2018
* http://gencat-presupuestos.gobify.net/mapas/2018
Redirects:
* http://gencat-presupuestos.gobify.net/places/25042/2015/redirect
* http://gencat-presupuestos.gobify.net/places/25042/redirect
* …

Support redirect with or without year

---

app/controllers/gobierto_budgets/places_controller.rb
app/models/gobierto_budgets/budget_line.rb
app/models/gobierto_budgets/budget_total.rb
app/models/gobierto_budgets/population.rb
app/models/gobierto_budgets/ranking.rb
app/views/gobierto_budgets/places/_ranking_table.html.erb
app/views/gobierto_budgets/places/_year_switcher.html.erb

This PR filters ES results fields to reduce the footprint of the response body. It also introduces some small optimization sin the code.
The improvement in staging is around 10% of speed and less CPU usage.

Speedup rankings

---

app/models/gobierto_budgets/budget_line.rb

Fixes https://github.com/PopulateTools/issues/issues/776
Check in http://presupuestos.gobify.net/ranking/2019/I/economic/amount?&amp;f[population][from]=100000&amp;f[population][to]=200000&amp;f[total][from]=0&amp;f[total][to]=5000000000&amp;f[per_inhabitant][from]=0&amp;f[per_inhabitant][to]=20000

Filter lines with custom code

---

app/controllers/gobierto_budgets/featured_budget_lines_controller.rb

This PR returns 404 when the budget line code parameter is invalid.
Fixes this noisy Rollbar: https://rollbar.com/Populate/gobierto-comparator/items/1771/?item_page=0&item_count=100&#instances

Return 404 not found on invalid embeds

---

app/models/gobierto_budgets/search_engine_configuration.rb

This PR activates 2020 data (following the process documented here: https://github.com/PopulateTools/gobierto/wiki/Updating-budgets-data)

Activate 2020 data

---

app/assets/javascripts/gobierto_budgets/ui.js
app/controllers/gobierto_budgets/places_controller.rb
app/helpers/gobierto_budgets/budget_line_widget_helper.rb

Closes https://github.com/PopulateTools/issues/issues/677
Closes https://github.com/PopulateTools/issues/issues/793
This PR fixes the parameters of the helper class, it was overwritting the url params instead of just setting the default if the parameter was empty

Fix budget lines switch

---

app/controllers/gobierto_budgets/api/global_data_controller.rb
app/models/gobierto_budgets/population.rb
app/models/gobierto_budgets/search_engine_configuration.rb

Closes https://github.com/PopulateTools/issues/issues/1196
This PR fixes how the population query was doing fallback to the previous year when data is not available.
This has started to be an issue since the change of year, as we haven't imported population data yet from 2020.
Working smoothly in http://presupuestos.gobify.net/

Fix fallback calculation for population queries

---

app/assets/javascripts/gobierto_budgets/ranking.js
app/controllers/gobierto_budgets/places_controller.rb
app/models/gobierto_budgets/budget_total.rb
app/models/gobierto_budgets/ranking.rb
app/views/gobierto_budgets/places/_ranking_table.html.erb

Closes https://github.com/PopulateTools/gobierto-comparador-presupuestos/issues/170
Closes https://github.com/PopulateTools/gobierto-comparador-presupuestos/issues/213
Fixes the CCAA filter, which was also broken

Fix ranking filter province

---

app/assets/javascripts/gobierto_budgets/maps.js
app/views/gobierto_budgets/pages/map.html.erb
config/settings/development.yml

- Increase the `maxZoom` property by one point.
- Set the version for the `deck.gl` to `8.4.0` to avoid errors in the future. Until now we had the latest version `<script src="https://unpkg.com/deck.gl@latest/dist.min.js"></script>`

Increase the maxZoom and set the version deck.gl to 8.4.0

---

Gemfile
Gemfile.lock
Rakefile
lib/tasks/gobierto_budgets/missing-categories.rake

Related to PopulateTools/issues#1352
This PR replaces namespaces of `GobiertoData` with `GobiertoBudgetsData` and updates the gems dependency to point `gobierto_budgets_data` instead of `gobierto_data`

1352 rename gobierto data

---

Gemfile
Gemfile.lock
config/environments/production.rb
config/environments/staging.rb

This PR enables LogRage logs when the environment variable `ENABLE_LOG_RAGE`  is set.
Logs look like this:
```
I, [2021-12-02T06:01:50.543346 #3061991]  INFO -- : method=GET path=/ranking format=html controller=GobiertoBudgets::PagesController action=ranking status=200 duration=49.50 view=40.98
I, [2021-12-02T06:01:50.773700 #3061991]  INFO -- : method=GET path=/api/data/widget/ranking/2021/G/functional/amount_per_inhabitant/336.json format=json controller=GobiertoBudgets::Api::DataController action=ranking status=200 duration=122.55 view=0.20
I, [2021-12-02T06:01:50.857505 #3061991]  INFO -- : method=GET path=/api/data/widget/ranking/2021/I/economic/amount/344.json format=json controller=GobiertoBudgets::Api::DataController action=ranking status=200 duration=77.19 view=0.09
I, …
```

Enable lograge logs

---

lib/tasks/gobierto_budgets/extra_data.rake

This PR introduces a task to load places debt and population using the data available at datos.gobierto.es
More info at the wiki: https://populate.getoutline.com/doc/periodical-data-load-budgets-population-debt-B4fuOxaLlS#h-loading-population-and-debt-for-budgets-module-and-gobierto-budgets-comparator

Task to load debt and population for all places

---

app/helpers/gobierto_helper.rb
app/views/layouts/gobierto_budgets_application.html.erb

Closes https://github.com/PopulateTools/gobierto-contratos/issues/3380
This PR adds a link to contratos.gobierto.es associated entity. The link is available in the footer, but can be moved elsewhere:
http://presupuestos.gobify.net/places/santander (gobierto / staging123)

Add link to contratos.gobierto.es

---

lib/tasks/gobierto_budgets/carto_csv.rake

This PR adds the force quotes option to the CSV dump used to load data in maps and data repositories.
Quotes are necessary because codes are strings not numbers, and without them the codes '01' and '011' are encoded as '1' and '11' which is not correct.

Force quotes in dumping budgets CSV

---

app/decorators/place_decorator.rb
lib/tasks/gobierto_budgets/budgets-import.rake
lib/tasks/gobierto_budgets/total-budget-import.rake

This PR:
* Extracts some logic related with places used to load data in elasticsearch to a decorator:
* The class defines 2 collections of decorated places, the INE::Places::Place full list used previously and a new `deputation_eu` collection with Euskadi foral deputatios
* The decorator provides some methods with attributes used to generate budget lines and code to search related data in the database
* Adds a new environment variable check `ENV["custom_place_id"]` which allows an implementation to select the places to import in the same way as is done setting a `ENV["place_id"]`, `ENV["province_id"]` or `ENV["autonomous_region_id"]`. The decorated deputation_eu collection provides a "deputation_eu" custom_place_id value for each member.
* Adds a check to detect which columns of each …

Add deputation data import

---

app/assets/javascripts/gobierto_budgets/ui.js
app/assets/javascripts/gobierto_budgets/visSlider.js
app/assets/javascripts/gobierto_budgets/vis_bubbles.js
app/controllers/gobierto_budgets/featured_budget_lines_controller.rb
app/controllers/gobierto_budgets/places_controller.rb
app/helpers/gobierto_budgets/budget_line_widget_helper.rb
app/models/gobierto_budgets/budget_line.rb
app/views/gobierto_budgets/places/_expense_lines.html.erb
app/views/gobierto_budgets/places/show.html.erb
app/views/gobierto_budgets/places/show.js.erb

Fixes PopulateTools/issues#1889
This PR:
* Changes data calculation in places controller show action to generate data of year updated in the controller to find a year with data
* Adds to the same action a request of expense data to check availability of existing data for functional and economic categories and hides the tab with missing data and changes the default expense data to be shown

Missing data improvements

---

app/assets/javascripts/gobierto_budgets/ui.js
app/controllers/application_controller.rb
app/views/layouts/gobierto_budgets_application.html.erb
app/views/layouts/gobierto_budgets_embedded.html.erb
config/settings/development.yml

This PR:
* Adds to the settings file a `combine_places_collections_in_searches` parameter which when enabled allows searches box to combine municipalities and deputations redirecting to the correct path depending on the entity type. This parameter is false by default
The feature can be checked in euskadi: https://ogp-euskadi.gobify.net/municipios allowing users to search by both municipalities and deputations in the same page
This PR fixes PopulateTools/issues#1953

Allow combining municipalities and deputations in searches

---

Gemfile
Gemfile.lock
config/puma.rb

This PR configures Puma as production server, with 2 workers per cluster, and just one cluster.
This PR should go together with:
- changes in the deploy https://github.com/PopulateTools/deploy-bot/pull/198
- changes in the Nginx virtual host

Configure puma as production server
