PopulateTools/gobierto-comparador-presupuestos

- lib/tasks/gobierto_budgets/carto_csv.rake
This PR creates a couple of Rake tasks to dump CSV data for CARTO
> Scripts to dump CSVs for CARTO

- app/assets/stylesheets/gobierto_budgets/application.scss
- app/assets/stylesheets/gobierto_budgets/map_page.scss
- app/views/sandbox/_map_metrics.html.erb
- app/views/sandbox/maps.html.erb
- Follows the Sketch layout
- Sample map
Fixes #2
> Create map page on Sandbox

- Capfile
- Gemfile
- Gemfile.lock
- bin/delayed_job
- config/application.rb
- config/deploy.rb
- spec/rails_helper.rb
This PR removes DJ for simplicity
> Remove delayed job

- .gitignore
- README.md
- app/controllers/application_controller.rb
- app/controllers/locale_controller.rb
- config/application.rb
- config/deploy.rb
- config/deploy/staging.rb
- config/deploy_secrets.yml.example
- config/routes.rb
> Change locale endpoint

- app/assets/javascripts/gobierto_budgets/vis_lineas_tabla.js
- app/models/gobierto_budgets/data/lines.rb
This PR removes the national mean from the comparisons when we are scoping places, because the measure doesn't make sense.
> Don't include national mean if places are scoped

- app/controllers/gobierto_budgets/api/data_controller.rb
- app/helpers/gobierto_budgets/application_helper.rb
- app/models/gobierto_budgets/budget_line.rb
- app/models/gobierto_budgets/budget_total.rb
- app/models/gobierto_budgets/population.rb
- app/views/gobierto_budgets/budget_lines/show.html.erb
- app/views/gobierto_budgets/places/_ranking_table.html.erb
- config/locales/defaults/ca.yml
- config/locales/defaults/en.yml
- config/locales/defaults/es.yml
- config/locales/views/ca.yml
- config/locales/views/en.yml
- config/locales/views/es.yml
- config/locales/views/gobierto_budgets/ca.yml
- config/locales/views/gobierto_budgets/en.yml
- config/locales/views/gobierto_budgets/es.yml
- config/locales/views/shared/ca.yml
- config/routes.rb
This PR fixes
- missing translations and typos
- data placeholder when users are not enabled
- error in rankings when applying a place scope
> Custom scope fixes

- app/helpers/gobierto_budgets/application_helper.rb
- app/views/gobierto_budgets/pages/home.html.erb
- app/views/gobierto_budgets/places/ranking.html.erb
- config/locales/views/gobierto_budgets/ca.yml
Fixes custom places scope for rankings
> Fixes custom places scope for rankings

- app/controllers/gobierto_budgets/api/data_controller.rb
- app/controllers/gobierto_budgets/places_controller.rb
- app/views/gobierto_budgets/pages/_map_metrics.html.erb
- app/views/gobierto_budgets/places/_place_widgets.html.erb
- app/views/shared/_widget_template_deviation.html.erb
- config/locales/views/gobierto_budgets/ca.yml
- config/locales/views/gobierto_budgets/en.yml
- config/locales/views/gobierto_budgets/es.yml
- config/locales/views/shared/ca.yml
- config/locales/views/shared/en.yml
- config/locales/views/shared/es.yml
Fix catalan typos 
Related with https://github.com/PopulateTools/gobierto-budgets-comparator-gen-cat/issues/7
> Catalan typos

- app/helpers/gobierto_budgets/application_helper.rb
- app/views/layouts/gobierto_budgets_application.html.erb
- app/views/layouts/gobierto_budgets_embedded.html.erb
- config/settings/development.yml
- config/settings/test.yml
Move @gobierto twitter handler to settings.
> Parameterize twitter handler

- app/assets/javascripts/gobierto_budgets/maps.js
Switch to ColorBrewer [YlGnBu](http://colorbrewer2.org/#type=sequential&scheme=YlGnBu&n=7), with 7 colors (instead of 5). Fixes #25.
> Change map color scheme

- app/assets/javascripts/gobierto_budgets/maps.js
- app/controllers/gobierto_budgets/places_controller.rb
- config/routes.rb
> Redirect to place when click in the map

- app/assets/stylesheets/gobierto_budgets/application.scss
- app/assets/stylesheets/gobierto_budgets/config.scss
- app/assets/stylesheets/gobierto_budgets/vis_legends.scss
- app/assets/stylesheets/gobierto_budgets/vis_lineas_j.scss
This PR fixes #30 by isolating the SCSS config and including the legend styles in a new file.
> Isolate SCSS config and fix line stats legend

- Gemfile
- Gemfile.lock
Unexpected.
Updates JSON gem version
> Update json version to 2.1.0

- app/models/gobierto_budgets/search_engine_configuration.rb
> Show 2018 data

- app/assets/javascripts/gobierto_budgets/vis_lineas_tabla.js
Please review in https://github.com/PopulateTools/gobierto/pull/1760 instead
> Fix budget line vis default year

- app/assets/javascripts/components/budgetLineTree.js
- app/assets/javascripts/gobierto_budgets/featured_budget_lines.js
- app/assets/javascripts/gobierto_budgets/ranking.js
- app/assets/stylesheets/gobierto_budgets/application.scss
- app/controllers/gobierto_budgets/api/global_data_controller.rb
- app/controllers/gobierto_budgets/places_controller.rb
- app/helpers/gobierto_budgets/ranking_table_helper.rb
- app/helpers/site_helper.rb
- app/models/concerns/gobierto_budgets/common_query_behavior.rb
- app/models/gobierto_budgets/budget_line.rb
- app/models/gobierto_budgets/budget_total.rb
- app/models/gobierto_budgets/population.rb
- app/models/gobierto_budgets/ranking.rb
- app/views/gobierto_budgets/places/_ranking_table.html.erb
- app/views/gobierto_budgets/places/ranking.html.erb
- app/views/gobierto_budgets/places/ranking.js.erb
- db/schema.rb
Closes #166 and [#612](https://github.com/PopulateTools/issues/issues/612)
> Fix ranking filters

- app/controllers/gobierto_budgets/api/data_controller.rb
- app/controllers/gobierto_budgets/featured_budget_lines_controller.rb
- app/helpers/gobierto_budgets/budget_line_widget_helper.rb
- app/views/gobierto_budgets/featured_budget_lines/_show.html.erb
- app/views/gobierto_budgets/featured_budget_lines/embed.html.erb
- app/views/layouts/embed.html.erb
- app/views/shared/_widget_template.new.html.erb
- app/views/shared/_widget_template_lite.new.html.erb
- config/environments/production.rb
You can check in the same page as before:
http://burjassot.gobify.net/pagina/mi-pagina
I've already visited several budget lines so you should be able to see the cache in action. When accepted, don't merge the PR, I'll update and deploy all the comparators etc.
> 186 - Faster featured budgets lines widget

- app/controllers/gobierto_budgets/places_controller.rb
- app/helpers/gobierto_budgets/budget_line_widget_helper.rb
- app/views/gobierto_budgets/places/show.html.erb
- app/views/shared/_widget_template.new.html.erb
Some places where previously it was breaking:
- http://presupuestos.gobify.net/places/badajoz/2018
- http://presupuestos.gobify.net/places/merida/2018
- http://presupuestos.gobify.net/places/ourense/2018
When approved it's pending to update the other comparators.
> Fix 404 featured budget line

- app/controllers/application_controller.rb
- public/robots.txt
This PR fixes the cache control header according to the CDN configuration.
> Configure cache control header for the CDN

- app/models/gobierto_budgets/budget_total.rb
- app/models/gobierto_budgets/population.rb
Fixes two annoying rollbars:
https://rollbar.com/Populate/gobierto-comparator/items/1760/?item_page=0&#instances
https://rollbar.com/Populate/gobierto-comparator/items/1762/
> Fix rollbars

- app/assets/javascripts/gobierto_budgets/ui.js
- app/views/gobierto_budgets/places/budget.js.erb
Fixes https://github.com/PopulateTools/issues/issues/777.
> Fix double rendering in budget line tree

- app/assets/javascripts/gobierto_budgets/maps.js
- app/views/gobierto_budgets/pages/map.html.erb
> Gobierto Data Token

- app/views/gobierto_budgets/places/_ranking_table.html.erb
Closes https://github.com/PopulateTools/issues/issues/1968
https://presupuestos.gobify.net/ranking/municipios/2023/I/economic/amount_per_inhabitant/344
> Table cell alignment

- Gemfile.lock
- app/controllers/application_controller.rb
- app/controllers/gobierto_budgets/api/categories_controller.rb
- app/controllers/gobierto_budgets/api/data_controller.rb
- app/controllers/gobierto_budgets/budget_lines_controller.rb
- app/controllers/gobierto_budgets/pages_controller.rb
- app/controllers/gobierto_budgets/places_controller.rb
This PR solves different cache issues:
- page cache doesn't include the locale in the generated file, so when the locale changes, the page content is wrong. I have replaced all page cache by action cache
- browser cache is causing some issues when switching the locale, since the cached version is returned but the content has changed. Now that we have a CDN in pro, browser cache doesn't seem so necessary
- updates gobierto_budgets_data gem with euskadi translations of categories
> Adjust cache issues

- app/views/gobierto_budgets/places/compare.html.erb
This PR avoids exceptions trying to extract values from empty data
> Avoid exceptions when total_line or population is empty

- app/controllers/application_controller.rb
- app/controllers/locale_controller.rb
- config/routes.rb
This PR prevents the infinite loop changing the locale
> Fix locale redirect infinite loop

- lib/tasks/gobierto_budgets/cache.rake
`bin/rails gobierto_budgets:cache:clear`
> Add a Rake task to clear app cache

- app/helpers/gobierto_budgets/application_helper.rb
- app/helpers/gobierto_budgets/budget_line_widget_helper.rb
- config/locales/views/gobierto_budgets/ca.yml
- config/locales/views/gobierto_budgets/en.yml
- config/locales/views/gobierto_budgets/es.yml
- Permits more specialized translations
- Fixes I18n locale missing param in cached fragments
> Adapt how translations are created to fix Euskera issues

- app/assets/javascripts/components/budgetLineTree.js
- app/assets/stylesheets/gobierto_budgets/application.scss
> Fix table text alignments

- app/helpers/gobierto_budgets/budget_line_widget_helper.rb
- app/models/gobierto_budgets/search_engine_configuration.rb
- Show 2024 data
- Fixes delta helper when the division is zero
> Add 2024 data year

- app/models/gobierto_budgets/search_engine_configuration.rb
> Set last data year to 2025
